[data-explorer][m]: refactored to work with data explorer concept. (#19)
* [data-explorer][m]: refactored to work with data explorer concept.

* update props of the App container
* update logic behind App container
* update fixtures to do dev with cosmos
* update unit tests

* [package][m]: Package App for distribution

* Add babel resources to package.json
* Add `yarn build:package` command
* Add updated resources at /dist

* [Chart][m]: added Chart component for rendering graphs from simple spec.

- includes fixtures for testing via cosmos

* [package][m]: Add dist files

* [tidy up][s]: refactored App.js to remove redundant code.

* [fixtures][xs]: fix loading fixture.

* [fixtures][xs]: fix failed fixture.

* [fixtures][xs]: fix map fixture.

* [Map][s]: fix popup on markers so it uses 'feature.properties.name' to display on click.

* [tests][xs]: mock Chart component as Plotly lib errors when running tests.

This means we aren't testing Chart compnent.

Error details:

  ● Test suite failed to run

    TypeError: Cannot read property 'document' of undefined

      1 | import React from 'react';
    > 2 | import Plotly from 'plotly.js-basic-dist';
        | ^
      3 | import createPlotlyComponent from "react-plotly.js/factory";
      4 |
      5 |

      at document (node_modules/plotly.js-basic-dist/plotly-basic.js:667:26)
      at Object.7 (node_modules/plotly.js-basic-dist/plotly-basic.js:660:2)
      at call (node_modules/plotly.js-basic-dist/plotly-basic.js:7:631)
      at o (node_modules/plotly.js-basic-dist/plotly-basic.js:7:682)
      at Object._dereq_ (node_modules/plotly.js-basic-dist/plotly-basic.js:36595:10)
      at call (node_modules/plotly.js-basic-dist/plotly-basic.js:7:631)
      at o (node_modules/plotly.js-basic-dist/plotly-basic.js:7:682)
      at Object._dereq_ (node_modules/plotly.js-basic-dist/plotly-basic.js:10:11)
      at call (node_modules/plotly.js-basic-dist/plotly-basic.js:7:631)
      at o (node_modules/plotly.js-basic-dist/plotly-basic.js:7:682)
      at Object._dereq_ (node_modules/plotly.js-basic-dist/plotly-basic.js:34001:1)
      at call (node_modules/plotly.js-basic-dist/plotly-basic.js:7:631)
      at o (node_modules/plotly.js-basic-dist/plotly-basic.js:7:682)
      at Object._dereq_ (node_modules/plotly.js-basic-dist/plotly-basic.js:99:18)
      at call (node_modules/plotly.js-basic-dist/plotly-basic.js:7:631)
      at o (node_modules/plotly.js-basic-dist/plotly-basic.js:7:682)
      at Object._dereq_ (node_modules/plotly.js-basic-dist/plotly-basic.js:112:14)
      at call (node_modules/plotly.js-basic-dist/plotly-basic.js:7:631)
      at o (node_modules/plotly.js-basic-dist/plotly-basic.js:7:797)
      at node_modules/plotly.js-basic-dist/plotly-basic.js:7:367
      at f (node_modules/plotly.js-basic-dist/plotly-basic.js:7:88)
      at Object.<anonymous> (node_modules/plotly.js-basic-dist/plotly-basic.js:7:1)
      at Object.<anonymous> (src/Chart.js:2:1)
      at Object.<anonymous> (src/App.js:6:1)
      at Object.<anonymous> (src/App.test.js:4:1)

* [tabularmap][m]: basic implementation of tabular map, eg, building Maps from tabular data.

* [tabularmap][xs]: fix confused order of lon and lat so that first one is lon.

* [tabularmap][m]: support JS string templates.

* [setup][l]: moved utils function into new module + implemented handling geometry field automatically

* [tests][xl]: fixtures and tests for auto detecting geometry fields

* [build:package]: to use it in data explorer

* [Map][xs]: zoom to fit all markers on the map

* [tests][s]: If running in JSDOM, we need to avoid using 'bounds' property of leaflet which causes the tests to crash.

* [Map][xs]: if no geo data in tabular data then render empty div element instead of failing.

* [bug fix][xs]: don't fail if no schema provided

* [setup][m]: use index.js for public interface only and setup all fixtures to use it.

Also updated the tests.

* [Map][s]: fix bug in Map renderer so simple GeoJSON also renders OK.

* [setup][xs]: package name update to invlude org name + major version release